# 出仓：数仓 DWS -> Doris 应用层
env {
  parallelism = 2
  job.mode = "BATCH"
}

source {
  Hive {
    database = "dws"
    table_name = "gmv_daily"
    result_table_name = "src_gmv"
  }
}

sink {
  Doris {
    fenodes = "doris-fe:8030"
    database = "app"
    table_name = "gmv_daily_rt"
    source_table_name = "src_gmv"
  }
}
