env {
  job.mode = "BATCH"
  parallelism = 2
}

source {
  FakeSource {
    schema = {
      fields {
        order_id = "long"
        product = "string"
        price = "double"
      }
    }
    row.num = 100
  }
}

sink {
  Console {}
}
