env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    schema = {
      fields {
        name = "string"
        age = "int"
        email = "string"
      }
    }
    rows = 10
  }
}

transform {
}

sink {
  Console {}
}
