env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  MySQL-CDC {
    hostname = "localhost"
    port = 3306
    database-name = "test_db"
    table-name = "users"
    username = "root"
    password = "password"
  }
}

transform {
}

sink {
  Console {}
}
