env {
  job.mode = "STREAMING"
  parallelism = 4
}

source {
  MySQL-CDC {
    hostname = "localhost"
    port = 3306
    database-name = "test_db"
    table-name = "users"
    username = "root"
    password = ""
  }
}

transform {}

sink {
  Console {}
}
